### ISSUE TITLE
Absolem Vector image not rendering/incorrect

### ISSUE THREAD

**Issue by aydenvis** [jhelvy/splitKbCompare#13]
![image](https://user-images.githubusercontent.com/38897937/85639766-64eac300-b64f-11ea-86f0-8ccfe9051cf8.png)

Seems like there should be a white line completing the board outline, but there is not.

**Comment by aydenvis** [comment]
Same for the Reviung 39, Dygma Raise, and Atreus.

**Comment by jhelvy** [comment]
All of the keyboards you listed are one-piece keyboards, but this app only compares the right hand of split boards since the left hand is just a mirror image. For the one-piece boards, I "cut" them into halves and only show the right hand. That's why the line around the board isn't completely closed on the left side - there's another half not shown. Does that make sense, and am I interpreting your question correctly?

**Comment by aydenvis** [comment]
Ah, that'd make sense, didn't catch that somehow, thanks for the
clarification!

**Comment by jhelvy** [comment]
No problem. Actually, based on this question I just added another filter to select boards that are one-piece boards vs. two halves :)
