### ISSUE TITLE
Add URL encoding

### ISSUE THREAD

**Issue by issmirnov** [jhelvy/splitKbCompare#54]
It would be really nice if the user selections of keyboards were URL encoded. This would make it possible to share links with people.

Example: if kyria and ergodox are selected, the URL could be: 
```
https://compare.splitkb.com/?keyboards=kyria,ergodox
```

This should be doable with minimal javascript changes.

**Comment by jhelvy** [comment]
I actually just implemented this a few days ago, but it's only one-way in that if you provide keyboard names in the url the app will initialize with those keyboards selected, but if you then select other boards the url will not update. So it's really only useful as a way to send someone a link that has the keyboards you want to compare already selected, for example:
https://jhelvy.shinyapps.io/splitkbcompare/?keyboards=kyria;ergodox

As you can see, I used semicolons to separate the keyboard names instead of commas. The keyboard names you have to pass in the url are the `id` variables in the [keyboards.csv](https://github.com/jhelvy/splitKbCompare/blob/master/keyboards.csv) file. 

Also, this only works with the root url to the actual app, which is https://jhelvy.shinyapps.io/splitkbcompare/ 

The compare.splitkb.com url is actually just another web page that embeds the actual app using iframe, so I have no way of actually interacting with the app through the url on that page.

**Comment by issmirnov** [comment]
Got it, thanks!
