### ISSUE TITLE
Add ergodash mini

### ISSUE THREAD

**Issue by mrkskk** [jhelvy/splitKbCompare#6]
Its the ergodash without the top row. But adding it would make visualisation og smaller split board together.

**Comment by jhelvy** [comment]
I could add this - can you send a link to an svg or otherwise vector graphic of the switch plate?

**Comment by jhelvy** [comment]
Do you mean the ErgoTravel?
https://github.com/jpconstantineau/ErgoTravel

**Comment by mrkskk** [comment]
No I mean this

https://github.com/omkbd/ErgoDash/tree/master/mini/Case

**Comment by jhelvy** [comment]
Oh, so it literally is just the ergodash without the top row. I'm hesitant to add this then, only because there's limited real estate on the app. It looks rather clear to me when comparing the ergodash to a smaller board like the kyria or corne. I can see how the keys line up with the top row of the smaller boards, and the extra number row on the ergodash would just not be there if it were the mini.

**Comment by mrkskk** [comment]
I see.

Better save some bytes for the other cool boards out there
