### ISSUE TITLE
Error: an error has occurred happens very frequently when using the site

### ISSUE THREAD

**Issue by molohov** [jhelvy/splitKbCompare#66]
![Screenshot_20211118-171447](https://user-images.githubusercontent.com/1013095/142527811-873b8504-0384-4cb8-baf0-16b1ad2a3ea3.png)

There is no direct way to replicate it, but it happens often enough with any combination of keyboards selected/unselected. Refreshing the page resolves the issue but loses previous selections.

**Comment by jhelvy** [comment]
Yeah this is just going to keep happening since it's hosted for free, there isn't much I can do to fix it. I'm pretty sure it mostly comes down to the server, and if it's being heavily used at the moment then it just can't keep up and errors. There is probably a lot I could do to make the app more efficient so it doesn't use so much power, but I really don't have time to dig into it. 

If you want a much faster and better experience where this doesn't happen, my recommendation is to just [run it locally](https://github.com/jhelvy/splitKbCompare#run-locally).
