### ISSUE TITLE
Crash after unselecting keyboards

### ISSUE THREAD

**Issue by Glitchy-Tozier** [jhelvy/splitKbCompare#74]
This happens every time i deselect a few (1-4) keyboards. It makes the website pretty unusable, unfortunately.

In the following example I selected the first 5 keyboards, then deselected the first one.
The console didn't show any new errors when the crash occured:

![image](https://user-images.githubusercontent.com/59611881/145564951-7331e650-7907-4d53-bedd-74d1c07b1449.png)

**Comment by jhelvy** [comment]
Yes, this is a common problem and was mentioned in #66 

As I wrote in the response to that issue, this is just going to keep happening since it's hosted for free, there isn't much I can do to fix it. If you want a much faster and better experience where this doesn't happen, my recommendation to just [run it locally](https://github.com/jhelvy/splitKbCompare#run-locally).

**Comment by Glitchy-Tozier** [comment]
That's unfortunate. Thank you for your quick response.

I might be wrong, but isn't there a way to let GitHub host the website (for free)? This might improve hosting.

**Comment by jhelvy** [comment]
GitHub hosts static sites, but this is an interactive [Shiny app](https://shiny.rstudio.com/) that requires computing in the background to handle responses to user input, so I can't host it on GitHub. The good thing though is that running it locally is super, super easy. After installing R and the required packages, it's one line of code in R: 

`shiny::runGitHub('jhelvy/splitKbCompare')`

That will open a browser and the experience will essentially be the same, but way faster and more stable.

I built this using Shiny because it's what I know, but I know there is likely a much simpler (and far better) approach using Javascript that allows the entire site to essentially be static. I just don't know enough to make it happen. If someone in this community is a web developer with the time and skills to do it, I'd love to see it built - all of the necessary files are here.

**Comment by Glitchy-Tozier** [comment]
Interesting! Up until now, I only knew R as a statistics-tool!

**Comment by jhelvy** [comment]
Yeah it's come quite a long way from its origins in stats. It's become quite a powerful language for a wide variety of applications.
