### ISSUE TITLE
Error when quickly selecting multiple keyboards

### ISSUE THREAD

**Issue by 73567876543783** [jhelvy/splitKbCompare#79]
Hi,

One of the reasons I first forked the code was because I experienced an error when selecting multiple keyboards. When experimenting locally this error never occurs. It probably is caused by the limits or configuration of the shinyapps.io server.

**Steps to reproduce:**
1. Open https://jhelvy.shinyapps.io/splitkbcompare/
2. Start selecting keyboards from the top without waiting for the image to render

After about 4 keyboards you'll receive the following error: 

> Error: An error has occurred. Check your logs or contact the app author for clarification.

**Possible fixes**
I think there are three ways to go about this. 
- Reduce the image size so the images are easier to render. The downside would be that an additional option should be implemented to get the full size image. 
- Postpone the rendering of the image until a button is pressed. This should be easy to implement, whilst still using the full resolution images. A downside is that an additional action is required from the user. It would reduce the load by a lot though. For example: currently four images are rendered if I select four keyboards, even if I'm only interested in 1.
- A combination of the above.

My preference would go out to the last option, but just a button would be a quicker fix. I'm of course interested in other/better solutions.

**Comment by jhelvy** [comment]
Yes, this is a common problem, mentioned in #66 and #74.

I noted there that running it locally is my current work around. 

Image size reductions could help, but the labels will get less legible with small resolution images. Plus it's still run on a free server with limitations, so it may not solve the problem.

The current process of generating the image overlays is quite computationally expensive, so that is where I think effort should be focused. Delaying the rendering until a button is pressed may solve it, but that would be a very annoying UI. There is probably a better solution somewhere in changing how the rendering is happening, perhaps with just a simple fixed time delay while rendering, but I haven't given it much thought. I'm also unsure of what the actual source of the problem is since I can't produce the error when running it locally. If you can try and probe for the source, that would help. 

You could also try hosting a fork of the repo on shinyapps.io yourself to try and find the source of the error, since it only happens when served there.

**Comment by 73567876543783** [comment]
Aha, of course I couldn't have been the only one that experienced this.

Agree that both solutions I proposed aren't ideal. Hosting it myself is a good idea. Maybe a simple time delay is already enough indeed. 

I'll add it to the todo list, referencing all issues.
