### ISSUE TITLE
Add Cantor

### ISSUE THREAD

**Issue by azzamsa** [jhelvy/splitKbCompare#84]
Please complete this checklist and submit your issue - I will do my best to add your keyboard as soon as I can:

- [X] Keyboard name: Cantor
- [] Url to vector graphic (e.g. svg, pdf, etc.) of switch plate:
- [X] Min and max number of keys: 42
- [X] Url to keyboard project source (if available): https://github.com/diepala/cantor
- [X] Url to store to buy keyboard (if available): https://shop.beekeeb.com/

---

Hi, I have opened the issue to add Cantor to SplitKbCompare https://github.com/diepala/cantor/issues/3, it has been two months now.
So, I think I need to take the matter into my own hand. I would like to compare it to Torn.

I have read the [instruction](https://github.com/jhelvy/splitKbCompare#added-new-keyboards) for adding a new keyboard, But I still don't get It. I can open the `images/overlays.ai` using Inkscape (I don't have Adobe Illustrator), but I don't have any idea what to do next. Also, I don't have any clue how to get the SVG. Is it via KiCad?

Thanks for splitKbCompare.

**Comment by jhelvy** [comment]
Just seeing this for the first time now (the original issue was on the [diepala/cantor](https://github.com/diepala/cantor) repo, so I never saw it). I hand-place the svg files in Illustrator, so it's a time-consuming process. Often times I need to adjust the labels of other boards so that they don't overlap, and I usually try to do a batch of boards at once. Once they're all aligned, I re-export all the layers as individual png files (Illustrator makes this easy).  

I haven't had any time to work on this over the past few months, but if I get some time in the next month or so I can try to add it myself.

**Comment by azzamsa** [comment]
> (the original issue was on the [diepala/cantor](https://github.com/diepala/cantor) repo, so I never saw it).

Yeah, I thought the addition of new keyboard can be done "easily" by the keyboard author. Turns out, it is not.

> I haven't had any time to work on this over the past few months, but if I get some time in the next month or so I can try to add it myself.

Thanks a lot.

**Comment by l4u** [comment]
@jhelvy Yeah I can realign it according to the J key. For the PNG and PDF export, do you have a recommended way to do it?

**Comment by l4u** [comment]
@jhelvy I've aligned it in the ai file. But I haven't regenerated the png files. What dpi should I export it?

**Comment by jhelvy** [comment]
Really sorry, but it's still not quite aligned right :(. The issue is scaling - the switch plate for the Cantor must be scaled up a little more. Not every board has the same scaling when imported into Illustrator. You have to make the whole image slightly larger. It takes iteration as you have to scale, align, scale, align to get it right. 

This shows you just how much manual work it takes to add more boards to the project. I wish I had an easier process but I just don't know any other way to do it. I can maybe try and add all the remaining boards one day later in July, but after that batch I won't be able to add anymore. Just don't have the time.

**Comment by l4u** [comment]
@jhelvy is it the scaling at the ai file or the generated png file?
From the overlays.ai, I can see 3w6 is having a 14mm switch hole, which is the same as the cantor image.
<img width="1196" alt="Screen Shot 2022-06-25 at 9 00 26 AM" src="https://user-images.githubusercontent.com/97841/175752235-3d3a4def-77fd-458c-99f5-ec501e5db9ae.png">

**Comment by jhelvy** [comment]
Actually I think you're right. I was comparing it to the corne, but it has slightly different spacing, so it just looked like it was off. When I compare it to the 3w6 is aligns:
<img width="687" alt="Screen Shot 2022-06-25 at 7 11 57 AM" src="https://user-images.githubusercontent.com/9012994/175771064-e3fa8615-d12f-4648-a57e-554ea3254ad0.png">

I just uploaded it to shinyapps.io so these updates should now be live.

**Comment by l4u** [comment]
@jhelvy probably the Corne plate includes laser kerf.

**Comment by jhelvy** [comment]
Yeah I don't know all the details of these things. Each plate file is unique and some include different things, so it's not a perfect comparison half the time. But it does the job well enough.
